### ISSUE TITLE
Sinalização

### ISSUE THREAD

**Issue by jtemporal** [pythonbrasil/pycon-amazonia-memorial#17]
Colocar o conteúdo "Sinalização" escrito pelo Nilo no arquivo correspondente
- [x] Colocar o conteúdo da seção de [Sinalização do arquivo original](https://www.dropbox.com/s/tr83g5j5amdkyxt/Pycon%20Amazônia%202017%20-%20Memorial%20da%20Organização%20do%20Evento.pdf?dl=0) no arquivo de [sinalizacao](/pythonbrasil/pycon-amazonia-memorial/blob/master/source/2017/sinalizacao.rst)

**Comment by jtemporal** [comment]
essa aqui é da @sbenza

**Comment by sbenza** [comment]
Obrigada! \o/

**Comment by jtemporal** [comment]
feito no #27
