### ISSUE TITLE
Complementar seção "Antes do evento"

### ISSUE THREAD

**Issue by jtemporal** [pythonbrasil/pycon-amazonia-memorial#2]
Completar a parte `Antes do Evento`
- [x] Colocar o conteúdo da seção de [Antes do evento do arquivo original](https://www.dropbox.com/s/tr83g5j5amdkyxt/Pycon%20Amazônia%202017%20-%20Memorial%20da%20Organização%20do%20Evento.pdf?dl=0) no arquivo de [organização](/pythonbrasil/pycon-amazonia-memorial/blob/master/source/2017/organizacao.rst)

**Comment by crismotinha** [comment]
Pull Request aberto https://github.com/pythonbrasil/pycon-amazonia-memorial/pull/29 <3
